# Generated by Django 3.2.6 on 2021-08-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(null=True)),
                ('syllabus', models.PositiveSmallIntegerField(null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('course_code', models.CharField(max_length=12, null=True)),
                ('course_trainer', models.CharField(blank=True, max_length=10, null=True)),
                ('course_duration', models.CharField(max_length=14)),
                ('parent_phone', models.CharField(max_length=13)),
                ('passport', models.CharField(blank=True, max_length=15, null=True)),
                ('mentor', models.CharField(max_length=10, null=True)),
                ('room_number', models.CharField(blank=True, max_length=3, null=True)),
                ('laptop_number', models.CharField(blank=True, max_length=10, null=True)),
                ('big_sister', models.CharField(max_length=15, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('nationality', models.CharField(choices=[('K', 'Kenya'), ('U', 'Uganda'), ('R', 'Rwanda')], max_length=1, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True)),
            ],
        ),
    ]
