# Generated by Django 3.2.6 on 2021-08-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='big_sister',
        ),
        migrations.RemoveField(
            model_name='course',
            name='email',
        ),
        migrations.RemoveField(
            model_name='course',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='laptop_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='course',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='course',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='course',
            name='room_number',
        ),
    ]
