# Generated by Django 3.2.6 on 2021-08-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_auto_20210830_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date',
        ),
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_trainer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
