# Generated by Django 3.2.5 on 2021-08-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=16, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('profession', models.CharField(max_length=12, null=True)),
                ('contract', models.FileField(null=True, upload_to='')),
                ('image', models.ImageField(null=True, upload_to='documents/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True)),
                ('biography', models.TextField(null=True)),
            ],
        ),
    ]
